import React, { useState } from 'react';
import {
  AlertCircle,
  Award,
  BookOpen,
  CheckCircle2,
  ChevronRight,
  Database,
  FileCheck,
  FileSpreadsheet,
  HeartPulse,
  Lock,
  Scale,
  ShieldCheck,
  Sparkles,
  Users,
  Zap,
} from 'lucide-react';
import { Patient } from '../types';

interface AiTrustCenterProps {
  patient: Patient;
}

export const AiTrustCenter: React.FC<AiTrustCenterProps> = ({ patient }) => {
  const [selectedProvenance, setSelectedProvenance] = useState<number>(0);

  const provenanceExamples = [
    {
      signal: 'Blood Pressure Stage 2 (148/94 mmHg)',
      timestamp: '2026-08-20 08:30 AM',
      source: 'Ambulatory Oscillometric Sphygmomanometer #SN-9428',
      guideline: 'ACC/AHA 2017 Hypertension Clinical Practice Guidelines (Threshold >= 140/90 mmHg)',
      aiWeight: '-28 pts deduction on Physical Vitals layer of HealthPulse',
      clinicalRationale:
        'Continuous sustained systolic elevation over 140 mmHg increases left ventricular afterload and endothelial sheer stress.',
    },
    {
      signal: 'HbA1c Elevation from 7.4% to 8.2%',
      timestamp: '2026-08-18 09:40 AM',
      source: 'High-Performance Liquid Chromatography (HPLC) Metabolic Report #LAB-2026-0881',
      guideline: 'ADA Standards of Medical Care in Diabetes 2026 (Individualized target < 7.0% - 7.5%)',
      aiWeight: '-26 pts deduction on Lab & Biomarker layer of HealthPulse',
      clinicalRationale:
        'A +0.8% delta signifies prolonged ambient hyperglycemia over preceding 90-120 days requiring regimen review.',
    },
    {
      signal: 'Emergent Microalbuminuria (UACR 42 mg/g)',
      timestamp: '2026-08-18 09:40 AM',
      source: 'Urinary Albumin / Creatinine Immunoassay #LAB-2026-0881',
      guideline: 'KDIGO 2024 Clinical Practice Guideline for Diabetes Management in CKD (UACR > 30 mg/g)',
      aiWeight: '-14 pts deduction and Trigger for Renal Escalation Alert',
      clinicalRationale:
        'Urinary albumin excretion between 30-300 mg/g represents early glomerular hyperfiltration and microvascular injury.',
    },
  ];

  return (
    <div className="space-y-6">
      {/* Header Banner */}
      <div className="bg-white rounded-2xl p-5 border border-[#E5EAEA] shadow-xs flex flex-wrap items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <ShieldCheck className="w-6 h-6 text-[#168A6A]" />
            <h1 className="text-xl sm:text-2xl font-bold text-[#16302A]">
              AI Trust, Medical Safety & Data Provenance Center
            </h1>
          </div>
          <p className="text-xs sm:text-sm text-[#64748B] mt-0.5">
            Transparent algorithmic governance, strict clinical safety guardrails, and deterministic explainability.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <span className="text-xs font-bold bg-[#E8F7F1] text-[#168A6A] px-3 py-1.5 rounded-xl flex items-center gap-1.5">
            <Lock className="w-4 h-4" />
            <span>100% Synthetic Patient Data &bull; HIPAA Safe</span>
          </span>
        </div>
      </div>

      {/* 4 Core Pillars of HealthNexus AI Safety */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-white rounded-2xl p-5 border border-[#E5EAEA] shadow-xs space-y-2">
          <div className="w-9 h-9 rounded-xl bg-[#E8F7F1] text-[#168A6A] flex items-center justify-center font-bold">
            1
          </div>
          <h3 className="font-bold text-sm text-[#16302A]">Decision Support, Not Replacement</h3>
          <p className="text-xs text-[#64748B] leading-relaxed">
            HealthNexus AI acts purely as an assistive decision-support layer. It NEVER replaces primary physician diagnosis or independently alters prescriptions.
          </p>
        </div>

        <div className="bg-white rounded-2xl p-5 border border-[#E5EAEA] shadow-xs space-y-2">
          <div className="w-9 h-9 rounded-xl bg-[#EAF4FB] text-[#3B82C4] flex items-center justify-center font-bold">
            2
          </div>
          <h3 className="font-bold text-sm text-[#16302A]">Transparent Provenance</h3>
          <p className="text-xs text-[#64748B] leading-relaxed">
            Every score deduction, alert ticket, and clinical question generated by the AI traces back to a verified lab value, vital reading, or peer-reviewed guideline.
          </p>
        </div>

        <div className="bg-white rounded-2xl p-5 border border-[#E5EAEA] shadow-xs space-y-2">
          <div className="w-9 h-9 rounded-xl bg-[#FEF3C7] text-[#D97706] flex items-center justify-center font-bold">
            3
          </div>
          <h3 className="font-bold text-sm text-[#16302A]">Anti-Hallucination Guardrails</h3>
          <p className="text-xs text-[#64748B] leading-relaxed">
            Structured biomarker parsing uses deterministic reference ranges. When ambiguous lab data is encountered, the engine explicitly alerts the clinician.
          </p>
        </div>

        <div className="bg-white rounded-2xl p-5 border border-[#E5EAEA] shadow-xs space-y-2">
          <div className="w-9 h-9 rounded-xl bg-[#F3E8FF] text-[#9333EA] flex items-center justify-center font-bold">
            4
          </div>
          <h3 className="font-bold text-sm text-[#16302A]">Whole Health Integration</h3>
          <p className="text-xs text-[#64748B] leading-relaxed">
            We bridge psychosomatic mental health with biometrics safely, providing gentle micro-interventions rather than clinical psychiatric diagnoses.
          </p>
        </div>
      </div>

      {/* Interactive Data Provenance Inspector */}
      <div className="bg-white rounded-2xl p-6 border border-[#E5EAEA] shadow-xs space-y-5">
        <div className="flex items-center justify-between pb-3 border-b border-[#E5EAEA]">
          <div className="flex items-center gap-2">
            <Database className="w-5 h-5 text-[#168A6A]" />
            <h3 className="font-bold text-base text-[#16302A]">Interactive Data Provenance & Guideline Citations</h3>
          </div>
          <span className="text-xs text-[#64748B]">Auditable Traceability</span>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-5">
          {/* Signal Selector */}
          <div className="lg:col-span-4 space-y-2">
            <span className="text-[11px] font-bold text-[#64748B] uppercase tracking-wider block">
              Monitored Clinical Signals
            </span>
            {provenanceExamples.map((item, idx) => (
              <button
                key={idx}
                onClick={() => setSelectedProvenance(idx)}
                className={`w-full text-left p-3.5 rounded-xl border text-xs transition-all ${
                  selectedProvenance === idx
                    ? 'bg-[#E8F7F1]/40 border-[#168A6A] font-bold text-[#16302A] shadow-xs'
                    : 'bg-[#F8FAFA] border-[#E5EAEA] text-[#64748B] hover:bg-white'
                }`}
              >
                <div className="flex items-center justify-between">
                  <span>{item.signal}</span>
                  <ChevronRight className="w-3.5 h-3.5" />
                </div>
              </button>
            ))}
          </div>

          {/* Provenance Card */}
          <div className="lg:col-span-8 bg-[#F8FAFA] rounded-2xl p-5 border border-[#E5EAEA] space-y-4">
            <div>
              <span className="text-[10px] font-bold uppercase tracking-wider text-[#168A6A] block">
                Selected Signal Provenance Audit
              </span>
              <h4 className="text-base font-extrabold text-[#16302A] mt-0.5">
                {provenanceExamples[selectedProvenance].signal}
              </h4>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5 text-xs">
              <div className="p-3 bg-white rounded-xl border border-[#E5EAEA] space-y-1">
                <span className="text-[10px] font-bold text-[#64748B] uppercase tracking-wider block">
                  Sensor / Laboratory Source
                </span>
                <p className="font-semibold text-[#16302A]">{provenanceExamples[selectedProvenance].source}</p>
                <span className="text-[10px] text-[#64748B] block">Recorded: {provenanceExamples[selectedProvenance].timestamp}</span>
              </div>

              <div className="p-3 bg-white rounded-xl border border-[#E5EAEA] space-y-1">
                <span className="text-[10px] font-bold text-[#64748B] uppercase tracking-wider block">
                  Algorithmic Scoring Weight
                </span>
                <p className="font-semibold text-[#DC5A5A]">{provenanceExamples[selectedProvenance].aiWeight}</p>
                <span className="text-[10px] text-[#64748B] block">Deterministic mathematical model</span>
              </div>
            </div>

            <div className="p-3.5 bg-white rounded-xl border border-[#E5EAEA] space-y-1 text-xs">
              <span className="text-[10px] font-bold text-[#168A6A] uppercase tracking-wider block flex items-center gap-1">
                <BookOpen className="w-3.5 h-3.5" />
                <span>Clinical Guideline Benchmark</span>
              </span>
              <p className="font-semibold text-[#16302A]">{provenanceExamples[selectedProvenance].guideline}</p>
              <p className="text-[#64748B] text-[11px] mt-1">{provenanceExamples[selectedProvenance].clinicalRationale}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
